# -*- coding: utf-8 -*-
"""计划1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q-M0jsfF-wOp0MWTfmt5oalCXx6TJrmh
"""

import pandas as pd

df=pd.read_excel('金融系统+实体行业+波动率数据+UPDATED.xlsx')
df=df.set_index('Date')
df

from statsmodels.tsa.stattools import grangercausalitytests
def run_granger_causality_tests(data, maxlag=2):
    results = {}
    for column in data.columns:
        results[column] = {}
        for other_column in data.columns:
            if column != other_column:
                result = grangercausalitytests(data[[column, other_column]], [maxlag])
                results[column][other_column] = result[maxlag][0]['ssr_chi2test'][1]
    return results

import networkx as nx
def build_dynamic_causality_network(results, threshold=0.05):
    G = nx.DiGraph()
    node_list=[]

    for cause_column in results:
        for effect_column, p_value in results[cause_column].items():
            significant =p_value < threshold
            if significant:
                if cause_column not in node_list:
                    G.add_node(cause_column)
                    node_list.append(cause_column)
                if effect_column not in node_list:
                    G.add_node(effect_column)
                    node_list.append(effect_column)
                G.add_edge(cause_column, effect_column)
    return G

df_daily=df
df_monthly = df.resample('M').mean()
df_quarterly = df.resample('Q').mean()
df_yearly = df.resample('Y').mean()

"""### 日度动态网络"""

results = run_granger_causality_tests(df_daily, maxlag=2)
G = build_dynamic_causality_network(results)

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=1000, node_color='skyblue', font_size=8, font_color='black', arrows=True)
plt.title("Daily Dynamic Causality Network")
plt.show()

"""### 月度动态网络"""

results = run_granger_causality_tests(df_monthly, maxlag=2)
G = build_dynamic_causality_network(results)

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=1000, node_color='skyblue', font_size=8, font_color='black', arrows=True)
plt.title("Monthly Dynamic Causality Network")
plt.show()

"""### 季度动态网络"""

results = run_granger_causality_tests(df_quarterly, maxlag=2)
G = build_dynamic_causality_network(results)

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=1000, node_color='skyblue', font_size=8, font_color='black', arrows=True)
plt.title("Quarterly Dynamic Causality Network")
plt.show()

"""### 年度动态网络"""

results = run_granger_causality_tests(df_yearly, maxlag=2)
G = build_dynamic_causality_network(results)

pos = nx.spring_layout(G)
nx.draw(G, pos, with_labels=True, node_size=1000, node_color='skyblue', font_size=8, font_color='black', arrows=True)
plt.title("Yearly Dynamic Causality Network")
plt.show()

